### ISSUE TITLE
Minor issue in Pivotal_Recommended-1.0.0.pdf 

### ISSUE THREAD

**Issue by Houlistonm** [pivotal-cf/docs-addon-compliance-tools#11]
[R-95-1] Check if SCTP is loaded
Should read 
[R-95-1] Check if STCP is loaded

[R-138] Check if SSH LoginGraceTime is set to one minute or less
Verify that the following command runs successfully
grep "^LoginGraceTime 120$" /etc/ssh/sshd_config

The test description says one minute, but the test is for two minutes (120 seconds).

Please reconcile

**Comment by jncd** [comment]
Hi @Houlistonm 
Thanks so much for reporting this issue. We've now scheduled a full review of the three PDFs that are downloadable from the Pivotal Network site for the Compliance Scanner for PCF.

**Comment by snneji** [comment]
Hi @Houlistonm, we looked into your issue. SCTP (Stream Control Transmission Protocol) is correct as it stands. However, the LoginGraceTime test has been fixed to check for less than one minute, as stated in the description. 

Thank you for taking the time to give us feedback.
